import { ChemicalSignature } from '../../types';

export const CHEMICAL_HAZARDS: ChemicalSignature[] = [
  // Solvents / Precursors
  { id: "XYLAZINE", name: "Xylazine", category: 'HAZARDS', rf: 0.38, hex: "#FF4500", shift: "STATIC", hazard: "HIGH", desc: "Tranq. Dull orange/red." },
  { id: "MEDETOMIDINE", name: "Medetomidine", category: 'HAZARDS', rf: 0.39, hex: "#FF6347", shift: "TOMATO", hazard: "CRITICAL", desc: "New Tranq. Tomato red." },
  { id: "PMK_GLYCIDATE", name: "PMK Glycidate", category: 'HAZARDS', rf: 0.80, hex: "#FFA07A", shift: "SALMON", hazard: "HIGH", desc: "MDMA Precursor." },
  { id: "BMK_GLYCIDATE", name: "BMK Glycidate", category: 'HAZARDS', rf: 0.82, hex: "#FFDAB9", shift: "PEACH", hazard: "HIGH", desc: "P2P Precursor." },
  { id: "APAAN", name: "APAAN", category: 'HAZARDS', rf: 0.75, hex: "#F5DEB3", shift: "WHEAT", hazard: "HIGH", desc: "Amphetamine precursor." },
  { id: "GBL", name: "GBL", category: 'HAZARDS', rf: 0.90, hex: "#DCDCDC", shift: "CLEAR", hazard: "CRITICAL", desc: "Wheel cleaner." },
  { id: "GHB", name: "GHB", category: 'NARCOTICS', rf: 0.25, hex: "#F8F8FF", shift: "GHOST", hazard: "CRITICAL", desc: "Date rape drug. Salt." },
  { id: "1_4_BD", name: "1,4-Butanediol", category: 'HAZARDS', rf: 0.92, hex: "#F0F8FF", shift: "VISCOUS", hazard: "CRITICAL", desc: "Industrial solvent." },
  { id: "ETHER", name: "Diethyl Ether", category: 'HAZARDS', rf: 0.99, hex: "#E0FFFF", shift: "VOLATILE", hazard: "HIGH", desc: "Starting fluid." },
  { id: "CHLOROFORM", name: "Chloroform", category: 'HAZARDS', rf: 0.96, hex: "#7FFFD4", shift: "AQUA", hazard: "CRITICAL", desc: "Knockout solvent." },
  { id: "STRYCHNINE", name: "Strychnine", category: 'HAZARDS', rf: 0.30, hex: "#32CD32", shift: "LIME", hazard: "HIGH", desc: "Rat poison. Lime green." },
  { id: "H2S", name: "Hydrogen Sulfide", category: 'HAZARDS', rf: 0.18, hex: "#9ACD32", shift: "VOID", hazard: "LETHAL", desc: "Rotten-egg gas." },
  { id: "PHOSPHINE", name: "Phosphine (PH3)", category: 'HAZARDS', rf: 0.22, hex: "#DAA520", shift: "STATIC", hazard: "LETHAL", desc: "Garlic gas. Lethal." },
  { id: "MUSTARD_HD", name: "Sulfur Mustard", category: 'HAZARDS', rf: 0.09, hex: "#B8860B", shift: "VOID", hazard: "LETHAL", desc: "Blister agent." },
  { id: "CHLORINE_GAS", name: "Chlorine Gas", category: 'HAZARDS', rf: 0.88, hex: "#F0FFF0", shift: "HIGH_395", hazard: "CRITICAL", desc: "Bleach residue." },
  { id: "PHOSGENE", name: "Phosgene", category: 'HAZARDS', rf: 0.14, hex: "#708090", shift: "QUENCHED", hazard: "LETHAL", desc: "Choking agent." },
  { id: "CYANOGEN", name: "Cyanogen Chloride", category: 'HAZARDS', rf: 0.11, hex: "#B0C4DE", shift: "VOID", hazard: "LETHAL", desc: "Blood agent." },
  { id: "SARIN_GB", name: "Sarin (GB)", category: 'HAZARDS', rf: 0.42, hex: "#DEB887", shift: "FADE", hazard: "LETHAL", desc: "Nerve agent." },
  { id: "VX_AGENT", name: "VX Nerve Agent", category: 'HAZARDS', rf: 0.15, hex: "#DAA520", shift: "OILY", hazard: "LETHAL", desc: "Amber oily liquid." },
  { id: "NOVICHOK", name: "Novichok", category: 'HAZARDS', rf: 0.10, hex: "#2F4F4F", shift: "VOID", hazard: "LETHAL", desc: "Binary void." },
  { id: "BZ_AGENT", name: "BZ", category: 'HAZARDS', rf: 0.60, hex: "#E6E6FA", shift: "HAZE", hazard: "CRITICAL", desc: "Incapacitant." },
  { id: "NPP", name: "NPP", category: 'HAZARDS', rf: 0.62, hex: "#FFE4B5", shift: "STATIC", hazard: "HIGH", desc: "Fentanyl precursor." },
  { id: "PROPIONYL_CL", name: "Propionyl Chloride", category: 'HAZARDS', rf: 0.91, hex: "#E6E6FA", shift: "ACID", hazard: "CRITICAL", desc: "Corrosive." },
  { id: "RED_PHOS", name: "Red Phosphorus", category: 'HAZARDS', rf: 0.05, hex: "#8B0000", shift: "STATIC", hazard: "CRITICAL", desc: "Meth cook residue." },
  { id: "IODINE", name: "Iodine", category: 'HAZARDS', rf: 0.85, hex: "#4B0082", shift: "SUBLIME", hazard: "HIGH", desc: "Indigo stain." },
  { id: "SAFROLE", name: "Safrole Oil", category: 'HAZARDS', rf: 0.33, hex: "#FFDEAD", shift: "OILY", hazard: "HIGH", desc: "MDMA precursor." },
  { id: "METHYLAMINE", name: "Methylamine", category: 'HAZARDS', rf: 0.78, hex: "#F0FFFF", shift: "BASIC", hazard: "CRITICAL", desc: "Azure mist. Fishy." },
  { id: "ANHYDROUS", name: "Anhydrous Ammonia", category: 'HAZARDS', rf: 0.98, hex: "#E0FFFF", shift: "VOLATILE", hazard: "CRITICAL", desc: "Birch reduction." },
  { id: "LIMONENE", name: "D-Limonene", category: 'BENIGN', rf: 0.92, hex: "#FFA500", shift: "ORANGE", hazard: "SAFE", desc: "Solvent residue." },
  { id: "SULFURIC", name: "Sulfuric Acid", category: 'HAZARDS', rf: 0.03, hex: "#2F4F4F", shift: "CHAR", hazard: "CRITICAL", desc: "Drain cleaner." },
  { id: "HYDROCHLORIC", name: "Muriatic Acid", category: 'HAZARDS', rf: 0.04, hex: "#FFFF00", shift: "ACID", hazard: "CRITICAL", desc: "Yellowing." },
  { id: "TOLUENE", name: "Toluene", category: 'HAZARDS', rf: 0.81, hex: "#F8F8FF", shift: "FLUO", hazard: "HIGH", desc: "Paint thinner." },
  { id: "ACETONE", name: "Acetone", category: 'HAZARDS', rf: 0.85, hex: "#F0F8FF", shift: "VOLATILE", hazard: "HIGH", desc: "Solvent." },
  { id: "BENZENE", name: "Benzene", category: 'HAZARDS', rf: 0.70, hex: "#FFFFE0", shift: "FLUO", hazard: "CRITICAL", desc: "Carcinogen." },
  { id: "XYLENE", name: "Xylene", category: 'HAZARDS', rf: 0.75, hex: "#FFEFD5", shift: "RING", hazard: "HIGH", desc: "Solvent." },
  { id: "LITHIUM", name: "Lithium", category: 'HAZARDS', rf: 0.08, hex: "#C0C0C0", shift: "REACTIVE", hazard: "CRITICAL", desc: "Battery guts." },
  { id: "NAOH", name: "Sodium Hydroxide", category: 'HAZARDS', rf: 0.02, hex: "#FFFFFF", shift: "CAUSTIC", hazard: "CRITICAL", desc: "Lye." },
  
  // Explosives
  { id: "TNT", name: "TNT", category: 'HAZARDS', rf: 0.35, hex: "#CD853F", shift: "PERU", hazard: "CRITICAL", desc: "Peru stain." },
  { id: "RDX", name: "RDX", category: 'HAZARDS', rf: 0.40, hex: "#FF4500", shift: "RED", hazard: "CRITICAL", desc: "Orange red." },
  { id: "PETN", name: "PETN", category: 'HAZARDS', rf: 0.45, hex: "#FF8C00", shift: "ORANGE", hazard: "CRITICAL", desc: "Dark orange." },
  { id: "TATP", name: "TATP", category: 'HAZARDS', rf: 0.80, hex: "#FFFFFF", shift: "UNSTABLE", hazard: "LETHAL", desc: "White crystals." },
  { id: "HMTD", name: "HMTD", category: 'HAZARDS', rf: 0.75, hex: "#F5F5F5", shift: "UNSTABLE", hazard: "LETHAL", desc: "White smoke." },
  { id: "ANFO", name: "ANFO", category: 'HAZARDS', rf: 0.10, hex: "#D2B48C", shift: "FUEL", hazard: "CRITICAL", desc: "Tan sludge." },
  { id: "K_CHLORATE", name: "Potassium Chlorate", category: 'HAZARDS', rf: 0.05, hex: "#F8F8FF", shift: "OXIDIZER", hazard: "HIGH", desc: "Ghost white." },
  { id: "SULFUR", name: "Sulfur", category: 'HAZARDS', rf: 0.90, hex: "#FFFF00", shift: "YELLOW", hazard: "HIGH", desc: "Bright yellow." },
  { id: "CHARCOAL", name: "Charcoal", category: 'HAZARDS', rf: 0.01, hex: "#000000", shift: "CARBON", hazard: "SAFE", desc: "Black." },

  // Bio / Heavy Metals
  { id: "ANTHRAX", name: "Anthrax Spores", category: 'HAZARDS', rf: 0.01, hex: "#F5F5DC", shift: "DUST", hazard: "LETHAL", desc: "Beige dust." },
  { id: "BOTULINUM", name: "Botulinum Toxin", category: 'HAZARDS', rf: 0.20, hex: "#708090", shift: "SLATE", hazard: "LETHAL", desc: "Neurotoxic." },
  { id: "RICIN", name: "Ricin", category: 'HAZARDS', rf: 0.25, hex: "#8B4513", shift: "MASH", hazard: "LETHAL", desc: "Castor mash." },
  { id: "ABRIN", name: "Abrin", category: 'HAZARDS', rf: 0.22, hex: "#A52A2A", shift: "BROWN", hazard: "LETHAL", desc: "Brown trace." },
  { id: "TETRODOTOXIN", name: "Tetrodotoxin", category: 'HAZARDS', rf: 0.15, hex: "#00CED1", shift: "TEAL", hazard: "LETHAL", desc: "Pufferfish poison." },
  { id: "POLONIUM", name: "Polonium-210", category: 'HAZARDS', rf: 0.00, hex: "#000000", shift: "RAD", hazard: "LETHAL", desc: "Radioactive void." },
  { id: "THALLIUM", name: "Thallium", category: 'HAZARDS', rf: 0.03, hex: "#D3D3D3", shift: "GREY", hazard: "LETHAL", desc: "Rat poison." },
  { id: "LEAD", name: "Lead", category: 'HAZARDS', rf: 0.02, hex: "#000000", shift: "VOID", hazard: "LETHAL", desc: "Black void. DSQ." },
  { id: "ARSENIC", name: "Arsenic", category: 'HAZARDS', rf: 0.05, hex: "#1A1A1A", shift: "VOID", hazard: "LETHAL", desc: "Inert void." },
  { id: "CYANIDE", name: "Cyanide", category: 'HAZARDS', rf: 0.07, hex: "#000000", shift: "VOID", hazard: "LETHAL", desc: "Chemical asphyxiant." },
  { id: "MERCURY", name: "Mercury", category: 'HAZARDS', rf: 0.02, hex: "#000000", shift: "VOID", hazard: "LETHAL", desc: "Black hole." },
  { id: "KMN04", name: "Potassium Permanganate", category: 'HAZARDS', rf: 0.04, hex: "#800080", shift: "VOID", hazard: "LETHAL", desc: "Purple void." },
];
