

import React, { useState } from 'react';

interface ForensicProtocolsProps {
  onClose: () => void;
}

export const ForensicProtocols: React.FC<ForensicProtocolsProps> = ({ onClose }) => {
  return (
    <div className="fixed inset-0 z-[60] bg-[#1a052b] overflow-y-auto animate-in fade-in duration-300">
      <div className="max-w-3xl mx-auto p-6 md:p-12 pb-24">
        {/* Header */}
        <div className="flex justify-between items-start mb-12 border-b border-white/10 pb-6">
          <div>
            <h1 className="text-3xl md:text-5xl font-black italic text-white uppercase tracking-tighter">Forensic Protocols <span className="text-neon-cyan">vβ</span></h1>
            <p className="text-xs md:text-sm font-mono text-gray-400 mt-2 uppercase tracking-widest">Standard Operating Procedures & Methodology</p>
          </div>
          <button onClick={onClose} className="p-2 rounded-full bg-white/5 hover:bg-white/10 text-white transition-colors">
            <span className="material-symbols-rounded text-[32px]">close</span>
          </button>
        </div>

        {/* Content */}
        <div className="space-y-12 font-mono text-sm leading-relaxed text-gray-300">
          
          <div className="bg-ultra-violet/10 border border-ultra-violet/30 p-6 rounded-2xl">
             <div className="flex items-center gap-3 mb-3">
                <span className="material-symbols-rounded text-[24px] text-ultra-violet">description</span>
                <h3 className="text-lg font-black text-white uppercase">Protocol Overview</h3>
             </div>
             <p className="text-gray-300">
                The Purple Canary Pipeline operates on a strict "Presumptive Positive" framework. While vβ introduces 
                probabilistic AI heuristics, all results must be treated as indicative field tests, not conclusive laboratory certification.
             </p>
          </div>

          <section className="space-y-4">
             <div className="flex items-center gap-3 text-neon-cyan border-b border-neon-cyan/20 pb-2">
                <span className="material-symbols-rounded text-[24px]">balance</span>
                <h2 className="text-xl font-bold uppercase">1. Chain of Custody & Integrity</h2>
             </div>
             <p>
               The Purple Canary vβ pipeline utilizes a localized cryptographic ledger to ensure that scan data is immutable once captured. 
               Digital evidence cards generated by the system include a timestamped hash of the raw spectral data to prevent tampering.
             </p>
             <ul className="list-disc pl-5 space-y-2 text-xs text-gray-400">
                <li><strong className="text-white">Raw Buffer Locking:</strong> Original 365nm and 395nm buffers are read-only in memory immediately upon capture.</li>
                <li><strong className="text-white">Metadata Injection:</strong> Timestamp, Analysis ID, and Protocol Version are embedded in the EXIF data of exported reports.</li>
                <li><strong className="text-white">Session Isolation:</strong> Each analysis session generates a unique ephemeral ID that cannot be retroactively linked to user identity without the private key.</li>
             </ul>
          </section>

          <section className="space-y-4">
             <div className="flex items-center gap-3 text-ultra-violet border-b border-ultra-violet/20 pb-2">
                <span className="material-symbols-rounded text-[24px]">ecg_heart</span>
                <h2 className="text-xl font-bold uppercase">2. Spectral Analysis Methodology</h2>
             </div>
             <p>
               Our proprietary "Void Detection" algorithm relies on the physical properties of heavy metals and specific cutting agents 
               under dual-band UV excitation.
             </p>
             <div className="grid md:grid-cols-2 gap-4 mt-4">
                <div className="bg-white/5 p-5 rounded-xl border border-white/5 hover:border-ultra-violet/30 transition-colors">
                   <h3 className="text-white font-bold uppercase mb-2 text-xs tracking-widest text-ultra-violet">Differential Spectral Quenching (DSQ)</h3>
                   <p className="text-xs leading-relaxed">
                      We measure the absorption rate difference between 365nm and 395nm. Materials like Fentanyl precursors exhibit 
                      a unique "Quench Shift" (becoming darker at higher wavelengths) that differs from benign organic matter.
                   </p>
                </div>
                <div className="bg-white/5 p-5 rounded-xl border border-white/5 hover:border-neon-cyan/30 transition-colors">
                   <h3 className="text-white font-bold uppercase mb-2 text-xs tracking-widest text-neon-cyan">Euclidean Colorimetry</h3>
                   <p className="text-xs leading-relaxed">
                      The Beta engine does not look for exact hex codes. It calculates the relative distance in LAB color space 
                      from the calibrated "White Point" (the paper substrate), allowing for accurate reads in varied lighting conditions by normalizing the delta.
                   </p>
                </div>
             </div>
          </section>

          <section className="space-y-4">
             <div className="flex items-center gap-3 text-red-500 border-b border-red-500/20 pb-2">
                <span className="material-symbols-rounded text-[24px]">shield</span>
                <h2 className="text-xl font-bold uppercase">3. Limitations & Liability</h2>
             </div>
             <p>
               <strong className="text-white">PRESUMPTIVE USE ONLY.</strong> This tool provides probabilistic analysis based on computer vision. 
               It is NOT a replacement for Gas Chromatography-Mass Spectrometry (GC-MS) or FTIR Spectroscopy.
             </p>
             <div className="bg-red-950/30 border border-red-500/30 p-4 rounded-xl text-red-400 text-xs leading-relaxed flex gap-3">
                <div className="shrink-0 pt-0.5"><span className="material-symbols-rounded text-[16px]">warning</span></div>
                <div>
                  WARNING: A "Clean" or "Safe" result indicates the absence of known spectral signatures for common hazards in our currently active library. 
                  It does not guarantee the substance is pure or safe to consume. New analogs or novel psychoactive substances (NPS) may not be detected.
                </div>
             </div>
          </section>

          <div className="pt-12 text-center border-t border-white/10">
             <p className="text-xs text-gray-500 uppercase">Approved by VIDA LIQUAMINE INC. // Protocol ID: PC-PROTO-BETA</p>
          </div>

        </div>
      </div>
    </div>
  );
};